apiVersion: v1
kind: Service
metadata:
  name: bill-service
  labels:
    app: bill
spec:
  selector:
    app: bill
  ports:
    - name: http
      port: 80
      targetPort: 8080   # <-- must match containerPort above
  type: NodePort
