apiVersion: v1
kind: Service
metadata:
  name: bill-service
  namespace: bill-ns
spec:
  selector:
    app: bill
  ports:
    - protocol: TCP
      port: 80
  type: NodePort   # or LoadBalancer if using a cloud provider
